alias ll='ls -lF --color=auto'
alias la='ls -AF --color=auto'
alias lla='ls -lAF --color=auto'
alias dir='ls -lF --color=auto'
alias gst='git status'
alias gsw='git switch'
alias gbr='git branch'
alias gfe='git fetch'
alias gpl='git pull'
alias gad='git add'
alias gcm='git commit'
alias gmg='git merge'
alias gpsh='git push'
alias ffmpeg='ffmpeg -hide_banner'
alias ffprobe='ffprobe -hide_banner'
#alias vdir='vdir --color=auto'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
